version: "2"
services:
  postgres:
    image: postgres:9.6.0
    container_name: pg-live
    networks:
      default:
        ipv4_address: "${LOCAL_POSTGRES}"
    extra_hosts:
    - "remote-pg:${REMOTE_POSTGRES}"
    volumes:
      - data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    environment:
      POSTGRES_USER: rutherford
      POSTGRES_PASSWORD: rutherf0rd

  postgres-create-blank-master:
    image: postgres:9.6.0
    volumes:
      - data:/var/lib/postgresql/data
      - ../isaac-api/src/main/resources/db_scripts/postgres-rutherford-create-script.sql:/docker-entrypoint-initdb.d/isaac-create.sql:ro
    environment:
      POSTGRES_USER: rutherford
      POSTGRES_PASSWORD: rutherf0rd
    command: postgres -V   

  postgres-create-standby:
    image: postgres:9.6.0
    networks:
      default:
        ipv4_address: "${LOCAL_POSTGRES}"
    extra_hosts:
    - "remote-pg:${REMOTE_POSTGRES}"
    volumes:
      - data:/var/lib/postgresql/data
      - ./recovery.conf:/recovery.conf
    command: /bin/sh -c "rm -rf /var/lib/postgresql/data/* && pg_basebackup -h remote-pg -D /var/lib/postgresql/data -U user -v -P && cp /recovery.conf /var/lib/postgresql/data/recovery.conf"

volumes:
  data:
    external:
      name: live-db-data

networks:
  default:
    external:
      name: isaac
