version: "2"
services:
  cs-pg:
    image: postgres:11
    container_name: cs-pg-live
    networks:
      default:
        ipv4_address: "${LOCAL_CS_POSTGRES_IP}"
    extra_hosts:
    - "remote-pg:${REMOTE_CS_POSTGRES_IP}"
    volumes:
      - data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - /local/data/postgres_home:/home/postgres
      - /local/data/postgres_home_root:/root
    environment:
      POSTGRES_USER: "rutherford"
      POSTGRES_PASSWORD: "${CS_POSTGRES_PASSWORD}"

  cs-pg-create-blank-master:
    image: postgres:11
    volumes:
      - data:/var/lib/postgresql/data
      - ../isaac-api/src/main/resources/db_scripts/postgres-rutherford-create-script.sql:/docker-entrypoint-initdb.d/00-isaac-create.sql:ro
      - ../isaac-api/src/main/resources/db_scripts/postgres-rutherford-functions.sql:/docker-entrypoint-initdb.d/01-isaac-functions.sql:ro
      - ../isaac-api/src/main/resources/db_scripts/quartz_scheduler_create_script.sql:/docker-entrypoint-initdb.d/02-isaac-quartz.sql:ro
    environment:
      POSTGRES_USER: "rutherford"
      POSTGRES_PASSWORD: "${CS_POSTGRES_PASSWORD}"
    command: postgres -V

  cs-pg-create-standby:
    image: postgres:11
    networks:
      default:
        ipv4_address: "${LOCAL_CS_POSTGRES_IP}"
    extra_hosts:
    - "remote-pg:${REMOTE_CS_POSTGRES_IP}"
    volumes:
      - data:/var/lib/postgresql/data
      - ./recovery.conf:/recovery.conf
    command: /bin/sh -c "rm -rf /var/lib/postgresql/data/* && pg_basebackup -P -h remote-pg -D /var/lib/postgresql/data -U rutherford -v -P && cp /recovery.conf /var/lib/postgresql/data/recovery.conf"

volumes:
  data:
    external:
      name: cs-live-db-data

networks:
  default:
    external:
      name: isaac
