services:
  sci-pg:
    image: postgres:18
    container_name: sci-pg-live
    shm_size: 512M
    networks:
      default:
        ipv4_address: "${LOCAL_SCI_POSTGRES_IP}"
    volumes:
      - /isaac/sci-live-db-pg18:/var/lib/postgresql
      - ./pg_hba.conf:/var/lib/postgresql/18/docker/pg_hba.conf:ro
      - ./postgresql.conf:/var/lib/postgresql/18/docker/postgresql.conf:ro
      - /local/data/postgres/sci-service.conf:/etc/postgresql-common/pg_service.conf:ro
      - /local/data/postgres/sci-keys:/keys:ro
      - /local/data/postgres_home_root:/root:rw
    restart: unless-stopped

  sci-pg-create-blank-master:
    image: postgres:18
    volumes:
      - /isaac/sci-live-db-pg18:/var/lib/postgresql
      - ../isaac-api/src/main/resources/db_scripts/postgres-rutherford-create-script.sql:/docker-entrypoint-initdb.d/00-isaac-create.sql:ro
      - ../isaac-api/src/main/resources/db_scripts/postgres-rutherford-functions.sql:/docker-entrypoint-initdb.d/01-isaac-functions.sql:ro
      - ../isaac-api/src/main/resources/db_scripts/quartz_scheduler_create_script.sql:/docker-entrypoint-initdb.d/02-isaac-quartz.sql:ro
    environment:
      POSTGRES_USER: rutherford
      POSTGRES_PASSWORD: "${SCI_POSTGRES_PASSWORD}"

  sci-pg-create-standby:
    image: postgres:18
    networks:
      default:
        ipv4_address: "${LOCAL_SCI_POSTGRES_IP}"
    volumes:
      - /isaac/sci-live-db-pg18:/var/lib/postgresql
      - /local/data/postgres/sci-service.conf:/etc/postgresql-common/pg_service.conf:ro
      - /local/data/postgres/sci-keys:/keys:ro
    command: /bin/sh -c "rm -rf /var/lib/postgresql/18/docker* && pg_basebackup -P -d 'service=primary-db' -D /var/lib/postgresql/18/docker -U rutherford -v -P && touch /var/lib/postgresql/18/docker/standby.signal"

networks:
  default:
    name: isaac
    external: true
